export const GET_LIST_MOVIES = "GET_LIST_MOVIES";
export const GET_LIST_MOVIES_SUCCESS = "GET_LIST_MOVIES_SUCCESS";
export const GET_LIST_MOVIES_ERROR = "GET_LIST_MOVIES_ERROR";
export const GET_LIST_MOVIES_CLEAR = "GET_LIST_MOVIES_CLEAR";

export const GET_MOVIE = "GET_MOVIE";
export const GET_MOVIE_CLEAR = "GET_MOVIE_CLEAR";
export const GET_MOVIE_ERROR = "GET_MOVIE_ERROR";
export const GET_MOVIE_SUCCESS = "GET_MOVIE_SUCCESS";

export const ADD_MOVIE_TO_FAVORITES = "ADD_MOVIE_TO_FAVORITES";
export const ADD_MOVIE_TO_FAVORITES_ERROR = "ADD_MOVIE_TO_FAVORITES_ERROR";
export const ADD_MOVIE_TO_FAVORITES_SUCCESS = "ADD_MOVIE_TO_FAVORITES_SUCCESS";

export const GET_FAVORITE_LIST_MOVIES = "GET_FAVORITE_LIST_MOVIES";
export const GET_FAVORITE_LIST_MOVIES_SUCCESS =
  "GET_FAVORITE_LIST_MOVIES_SUCCESS";
export const GET_FAVORITE_LIST_MOVIES_ERROR = "GET_FAVORITE_LIST_MOVIES_ERROR";
export const GET_FAVORITE_LIST_MOVIES_CLEAR = "GET_FAVORITE_LIST_MOVIES_CLEAR";

export const REMOVE_MOVIE_FROM_FAVORITES = "REMOVE_MOVIE_FROM_FAVORITES";
export const REMOVE_MOVIE_FROM_FAVORITES_ERROR =
  "REMOVE_MOVIE_FROM_FAVORITES_ERROR";
export const REMOVE_MOVIE_FROM_FAVORITES_SUCCESS =
  "REMOVE_MOVIE_FROM_FAVORITES_SUCCESS";

export const FILTER_LIST_OF_MOVIES = "FILTER_LIST_OF_MOVIES";
export const FILTER_LIST_OF_MOVIES_SUCCESS = "FILTER_LIST_OF_MOVIES_SUCCESS";
export const FILTER_LIST_OF_MOVIES_ERROR = "FILTER_LIST_OF_MOVIES_ERROR";
